[package]
name = "perDiem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
either = "1.9.0"
cond_utils = "0.1.0"
regex = "1.10.2"
[profile.dev]
opt-level = 3  